In [52]:
import pandas as pd

df = pd.read_csv("StudentPerformanceFactors.csv")
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [5]:
df.shape

(6607, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
Hours_Studied                 6607 non-null int64
Attendance                    6607 non-null int64
Parental_Involvement          6607 non-null object
Access_to_Resources           6607 non-null object
Extracurricular_Activities    6607 non-null object
Sleep_Hours                   6607 non-null int64
Previous_Scores               6607 non-null int64
Motivation_Level              6607 non-null object
Internet_Access               6607 non-null object
Tutoring_Sessions             6607 non-null int64
Family_Income                 6607 non-null object
Teacher_Quality               6529 non-null object
School_Type                   6607 non-null object
Peer_Influence                6607 non-null object
Physical_Activity             6607 non-null int64
Learning_Disabilities         6607 non-null object
Parental_Education_Level      6517 non-null object
Distance_from_Home            6540 non-null object
Gender                        6607 non-null object
Exam_Score                    6607 non-null int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [7]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [53]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [54]:
df['Teacher_Quality'].fillna('Unknown', inplace=True)
df['Parental_Education_Level'].fillna('Unknown', inplace=True)
df['Distance_from_Home'].fillna('Unknown', inplace=True)

In [55]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score]
Index: []

In [91]:
df['At_Risk'] = df['Exam_Score'].apply(lambda x: 1 if x < 65 else 0)

In [109]:
categorical_cols = df.select_dtypes(include=['object']).columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

In [93]:
encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [94]:
encoded.columns

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score', 'At_Risk',
       'Parental_Involvement_Low', 'Parental_Involvement_Medium',
       'Access_to_Resources_Low', 'Access_to_Resources_Medium',
       'Extracurricular_Activities_Yes', 'Motivation_Level_Low',
       'Motivation_Level_Medium', 'Internet_Access_Yes', 'Family_Income_Low',
       'Family_Income_Medium', 'Teacher_Quality_Low', 'Teacher_Quality_Medium',
       'Teacher_Quality_Unknown', 'School_Type_Public',
       'Peer_Influence_Neutral', 'Peer_Influence_Positive',
       'Learning_Disabilities_Yes', 'Parental_Education_Level_High School',
       'Parental_Education_Level_Postgraduate',
       'Parental_Education_Level_Unknown', 'Distance_from_Home_Moderate',
       'Distance_from_Home_Near', 'Distance_from_Home_Unknown', 'Gender_Male'],
      dtype='object')

In [95]:
encoded['At_Risk'].value_counts(normalize=True)

0    0.780233
1    0.219767
Name: At_Risk, dtype: float64

In [110]:
encoded[numerical_cols].describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [111]:
Q1 = encoded[numerical_cols].quantile(0.25)
Q3 = encoded[numerical_cols].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [128]:
outliers = encoded[(encoded < lower_bound) | (encoded > upper_bound)]
outlier_rows = outliers.dropna(how="all")
(encoded < lower_bound).sum() + (encoded > upper_bound).sum()
# outlier_rows

Access_to_Resources_Low                     0
Access_to_Resources_Medium                  0
At_Risk                                     0
Attendance                                  0
Distance_from_Home_Moderate                 0
Distance_from_Home_Near                     0
Distance_from_Home_Unknown                  0
Exam_Score                                104
Extracurricular_Activities_Yes              0
Family_Income_Low                           0
Family_Income_Medium                        0
Gender_Male                                 0
Hours_Studied                            5582
Internet_Access_Yes                         0
Learning_Disabilities_Yes                   0
Motivation_Level_Low                        0
Motivation_Level_Medium                     0
Parental_Education_Level_High School        0
Parental_Education_Level_Postgraduate       0
Parental_Education_Level_Unknown            0
Parental_Involvement_Low                    0
Parental_Involvement_Medium                 0
Peer_Influence_Neutral                      0
Peer_Influence_Positive                     0
Physical_Activity                           0
Previous_Scores                             0
School_Type_Public                          0
Sleep_Hours                                 0
Teacher_Quality_Low                         0
Teacher_Quality_Medium                      0
Teacher_Quality_Unknown                     0
Tutoring_Sessions                         430
dtype: int64

In [126]:
encoded.loc[encoded["Hours_Studied"] > 10, "Hours_Studied"] //= 7
encoded["Hours_Studied"] = encoded["Hours_Studied"].astype(int)

In [127]:
hours_studied_outliers = encoded[encoded["Hours_Studied"] > 5]
hours_studied_outliers

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score,At_Risk,Parental_Involvement_Low,Parental_Involvement_Medium,...,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Parental_Education_Level_High School,Parental_Education_Level_Postgraduate,Parental_Education_Level_Unknown,Distance_from_Home_Moderate,Distance_from_Home_Near,Distance_from_Home_Unknown,Gender_Male
13,9,82,8,72,2,3,66,0,0,1,...,0,1,0,0,1,0,0,1,0,1
14,10,78,8,74,1,4,65,0,0,1,...,1,0,0,0,1,0,0,1,0,1
37,8,99,9,54,2,5,67,0,0,1,...,1,0,0,0,1,0,0,1,0,0
49,9,77,5,57,2,3,63,1,0,1,...,1,0,0,1,0,0,0,1,0,1
79,8,61,7,54,1,3,60,1,0,1,...,0,1,0,0,0,0,0,1,0,1
110,8,77,6,87,0,2,63,1,0,0,...,1,0,0,1,0,0,1,0,0,1
142,10,82,8,70,3,1,64,1,0,1,...,0,1,1,0,1,0,0,1,0,0
209,6,86,7,97,2,1,78,0,0,0,...,0,1,0,1,0,0,0,1,0,0
221,9,96,4,82,0,4,67,0,0,1,...,0,1,0,0,0,0,0,1,0,1
223,10,64,7,64,0,4,60,1,0,1,...,0,1,1,1,0,0,1,0,0,0
236,8,71,8,75,0,3,61,1,0,0,...,0,1,0,1,0,0,0,1,0,1
285,8,73,7,60,0,3,60,1,0,1,...,1,0,0,1,0,0,0,1,0,0
382,7,82,8,56,0,2,62,1,0,0,...,0,0,0,1,0,0,0,0,0,1
396,10,80,6,93,4,3,67,0,0,0,...,0,0,0,0,0,0,1,0,0,0
400,10,96,6,80,0,4,67,0,0,0,...,1,0,0,1,0,0,1,0,0,0
429,9,74,7,66,1,3,62,1,0,1,...,1,0,0,1,0,0,0,0,0,0
431,8,100,8,92,1,3,70,0,0,0,...,1,0,0,0,1,0,1,0,0,0
438,10,76,8,76,2,3,64,1,1,0,...,0,1,1,0,1,0,1,0,0,1
442,8,89,7,81,4,3,67,0,0,1,...,1,0,0,0,0,0,0,1,0,1
471,6,93,7,52,0,2,64,1,0,1,...,1,0,0,0,0,0,0,1,0,0
482,10,87,6,83,0,4,63,1,0,1,...,0,1,0,1,0,0,0,1,0,1
520,10,89,8,69,3,4,63,1,1,0,...,0,0,0,0,0,0,1,0,0,1
525,9,79,7,90,1,3,63,1,0,1,...,1,0,0,1,0,0,0,1,0,1
526,10,81,8,99,2,4,67,0,0,0,...,0,1,0,0,1,0,1,0,0,0
531,10,62,7,68,3,3,61,1,0,1,...,1,0,0,0,1,0,0,1,0,1
566,8,86,6,50,1,2,65,0,0,1,...,0,1,0,0,0,0,0,1,0,1
568,9,84,7,92,1,4,66,0,0,0,...,0,0,0,0,1,0,0,1,0,1
575,7,86,9,88,2,2,63,1,0,1,...,0,0,0,0,0,0,0,1,0,0
608,9,64,5,73,1,4,61,1,0,1,...,0,1,0,0,0,0,0,1,0,1
630,10,71,7,55,2,3,63,1,0,1,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5917,9,67,8,54,3,5,63,1,0,1,...,0,1,0,0,0,0,1,0,0,1
5924,9,91,4,88,2,4,65,0,0,1,...,1,0,1,0,1,0,0,1,0,0
5933,6,83,6,89,1,4,65,0,0,1,...,0,1,0,0,1,0,0,1,0,0
5948,10,75,4,90,3,3,65,0,0,1,...,0,1,1,0,1,0,1,0,0,1
5973,7,94,9,57,2,3,66,0,0,1,...,0,0,0,0,1,0,0,1,0,0
6007,10,61,10,79,4,2,62,1,0,0,...,0,1,1,0,0,0,1,0,0,1
6028,8,99,6,73,1,3,68,0,0,1,...,0,1,0,1,0,0,0,0,0,0
6030,10,98,7,80,3,3,69,0,0,1,...,1,0,0,0,0,0,0,1,0,1
6037,10,62,7,51,1,2,61,1,0,0,...,0,1,0,1,0,0,0,1,0,1
6182,10,81,8,63,1,2,64,1,0,1,...,1,0,0,0,0,1,0,1,0,1
6215,10,94,9,65,3,2,65,0,0,1,...,0,0,0,1,0,0,1,0,0,0
6248,10,88,9,60,1,3,63,1,1,0,...,0,1,0,1,0,0,1,0,0,0
6255,7,73,7,75,1,3,64,1,0,1,...,0,1,0,0,0,0,0,1,0,1
6304,8,68,7,96,2,3,65,0,0,0,...,0,1,0,0,1,0,0,1,0,0
6354,8,65,7,83,3,4,60,1,0,1,...,0,0,0,1,0,0,0,1,0,0
6358,8,64,7,66,1,3,60,1,0,1,...,0,1,0,0,0,0,0,1,0,1
6367,6,84,6,88,1,5,65,0,0,1,...,0,1,0,0,1,0,1,0,0,1
6390,8,96,8,100,1,4,68,0,0,1,...,0,0,0,1,0,0,1,0,0,1
6392,10,95,5,93,0,3,69,0,0,1,...,0,1,0,1,0,0,1,0,0,1
6412,9,98,9,64,1,3,67,0,0,0,...,0,0,0,1,0,0,0,1,0,1
6440,9,78,9,57,1,5,63,1,0,0,...,0,1,0,1,0,0,1,0,0,0
6448,6,67,6,99,0,2,60,1,0,1,...,1,0,0,0,0,0,0,1,0,1
6473,6,88,7,73,3,3,67,0,0,0,...,1,0,0,0,0,0,0,1,0,1
6474,9,89,6,96,0,4,66,0,0,1,...,0,0,0,1,0,0,0,1,0,1
6481,8,77,7,90,1,0,61,1,0,1,...,1,0,0,1,0,0,1,0,0,1
6542,9,82,6,86,2,2,64,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6579,9,84,6,74,5,2,67,0,0,1,...,1,0,0,1,0,0,0,1,0,1
6594,9,90,7,79,4,4,70,0,0,0,...,0,1,0,1,0,0,0,0,1,1
6598,9,87,6,64,1,2,64,1,1,0,...,1,0,0,1,0,0,0,1,0,0
6605,10,86,6,91,2,3,68,0,0,0,...,0,1,0,1,0,0,0,0,0,0

In [129]:
encoded.to_csv("cleaned_dataset.csv", index=False)

In [77]:
X = encoded.drop('At_Risk', axis=1)
y = encoded['At_Risk']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)